# Quench configuration
# https://github.com/alfredjeanlab/quench
version = 1

[check.cloc]
check = "error"

[check.escapes]
check = "error"

[check.agents]
check = "error"

[check.docs]
check = "error"

[check.tests]
check = "off"  # stub in quench v0.3.0

[check.license]
check = "off"  # stub in quench v0.3.0

[git.commit]
check = "off"  # stub in quench v0.3.0

# Supported Languages:
# [rust], [golang], [javascript], [shell]
