[javascript]
# source = ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "**/*.mjs", "**/*.mts"]
# tests = ["**/*.test.*", "**/*.spec.*", "**/test/**", "**/tests/**", "**/__tests__/**"]

[javascript.suppress]
check = "comment"

[javascript.policy]
lint_changes = "standalone"
